DROP TABLE IF EXISTS 
	WordInPost,
	Post,
	Word,
	User;

CREATE TABLE User
(
	UserId INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Username VARCHAR(250) NOT NULL, 
	SameAsUserId INT(11) UNSIGNED NULL,

	PRIMARY KEY (UserId)
)
ENGINE=INNODB;

CREATE TABLE WordInPost
(
	PostId INT(11) UNSIGNED NOT NULL,
	WordId INT(11) UNSIGNED NOT NULL,
	Position INT(11) UNSIGNED NOT NULL, 

	PRIMARY KEY (PostId, WordId)
)
ENGINE=INNODB;

CREATE TABLE Word
(
	WordId INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Word VARCHAR(250) NOT NULL,
	LookupPerformed BIT(1) NOT NULL DEFAULT 0,
	Swear BIT(1) NOT NULL DEFAULT 0,

	PRIMARY KEY (WordId)
)
ENGINE=INNODB;

CREATE TABLE Post
(
	PostId INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	UserId INT(11) UNSIGNED NOT NULL,
	Timestamp DATETIME NOT NULL,
	WordCount INT(11) UNSIGNED NULL,
	UniqueWordCount INT(11) UNSIGNED NULL, 
	IgnorePost BIT(1) NOT NULL DEFAULT 0,

	PRIMARY KEY (PostId)
)
ENGINE=INNODB;

ALTER TABLE WordInPost ADD FOREIGN KEY (PostId) REFERENCES Post(PostId);
ALTER TABLE WordInPost ADD FOREIGN KEY (WordId) REFERENCES Word(WordId);
ALTER TABLE Post ADD FOREIGN KEY (UserId) REFERENCES User(UserId);