

CREATE TABLE IF NOT EXISTS User
(
	UserId INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Username VARCHAR(250) NOT NULL, 
	SameAsUserId INT(11) UNSIGNED NULL,

	PRIMARY KEY (UserId),
	UNIQUE KEY idxUserUsername (Username)
)
ENGINE=INNODB;


CREATE TABLE WordInPost
(
	PostId INT(11) UNSIGNED NOT NULL,
	WordId INT(11) UNSIGNED NOT NULL,
	Position INT(11) UNSIGNED NOT NULL, 

	PRIMARY KEY (PostId, WordId, Position),
	INDEX (postId),
	INDEX (WordId)
)
ENGINE=INNODB;

CREATE TABLE Word
(
	WordId INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Word VARCHAR(250) NOT NULL,
	DictionaryWord BIT(1) NOT NULL DEFAULT 0,
	Swear BIT(1) NOT NULL DEFAULT 0,

	PRIMARY KEY (WordId)
)
ENGINE=INNODB;

CREATE TABLE Post
(
	PostId INT(11) UNSIGNED NOT NULL,
	UserId INT(11) UNSIGNED NOT NULL,
	Timestamp DATETIME NOT NULL,
	WordCount INT(11) UNSIGNED NULL,
	UniqueWordCount INT(11) UNSIGNED NULL, 
	IgnorePost BIT(1) NOT NULL DEFAULT 0,
	Removed BIT(1) NOT NULL DEFAULT 0,

	PRIMARY KEY (PostId)
)
ENGINE=INNODB;

ALTER TABLE WordInPost ADD FOREIGN KEY (PostId) REFERENCES Post(PostId);
ALTER TABLE WordInPost ADD FOREIGN KEY (WordId) REFERENCES Word(WordId);
ALTER TABLE Post ADD FOREIGN KEY (UserId) REFERENCES User(UserId);

CREATE TABLE DictionaryLookup
(
	Date DATE NOT NULL,
	Count INT(6) UNSIGNED NOT NULL DEFAULT 0,

	PRIMARY KEY (Date)
)
ENGINE=INNODB;


